Repository MagaluCloud/magalu, pull requests merged in 2024-11, with the labels that each got.

#1235 chore: check duplicated paths oas
  mgc/sdk/openapi/operation_table.go
  mgc/sdk/openapi/operation_table_test.go
  mgc/spec_manipulator/cmd/download.go
  mgc/spec_manipulator/cmd/prepare.go
  mgc/spec_manipulator/go.mod
Labels: enhancement

#1244 chore: update virtual machine specifications
  mgc/cli/docs/virtual-machine/images/list/help.md
  mgc/cli/docs/virtual-machine/instances/create/help.md
  mgc/cli/docs/virtual-machine/instances/list/help.md
  mgc/cli/docs/virtual-machine/machine-types/list/help.md
  mgc/cli/docs/virtual-machine/snapshots/list/help.md
  mgc/cli/openapis/virtual-machine.openapi.yaml
  mgc/lib/go.mod
  mgc/lib/products/doc.go
  mgc/lib/products/virtual_machine/images/list.go
  mgc/lib/products/virtual_machine/instances/get.go
  mgc/lib/products/virtual_machine/instances/list.go
  mgc/lib/products/virtual_machine/machine_types/list.go
  mgc/lib/products/virtual_machine/snapshots/copy.go
  mgc/lib/products/virtual_machine/snapshots/service.go
  mgc/sdk/openapi/embed_loader.go
  mgc/spec_manipulator/cli_specs/conv.virtual-machine.jaxyendy.openapi.json
  mgc/spec_manipulator/cli_specs/virtual-machine.jaxyendy.openapi.json
Labels: enhancement

#1243 chore: update tf docs
  .github/workflows/release.yaml
Labels: terraform

#1245 feat: add new scope pa:sa:manage
  mgc/sdk/static/auth/login.go
Labels: cli

#1246 chore: update network specifications
  mgc/cli/docs/network/security_groups/rules/create/help.md
  mgc/cli/docs/network/vpcs/create/help.md
  mgc/cli/docs/network/vpcs/subnets/create/help.md
  mgc/cli/openapis/index.openapi.yaml
  mgc/cli/openapis/network.openapi.yaml
  mgc/sdk/openapi/embed_loader.go
  mgc/spec_manipulator/cli_specs/conv.network.jaxyendy.openapi.json
  mgc/spec_manipulator/cli_specs/network.jaxyendy.openapi.json
Labels: cli, core

#1247 chore: change query-param
  mgc/sdk/openapi/operation.go
Labels: cli, core

#1248 chore: update block storage spec
  mgc/cli/docs/block-storage/snapshots/list/help.md
  mgc/cli/docs/block-storage/volume-types/list/help.md
  mgc/cli/docs/block-storage/volumes/list/help.md
  mgc/cli/openapis/block-storage.openapi.yaml
  mgc/sdk/openapi/embed_loader.go
  mgc/spec_manipulator/cli_specs/block-storage.jaxyendy.openapi.json
  mgc/spec_manipulator/cli_specs/conv.block-storage.jaxyendy.openapi.json
Labels: cli

#1251 fix: infinite loop when no API key or access token is provided
  mgc/core/auth/auth.go
  mgc/sdk/go.mod
  mgc/sdk/go.sum
  mgc/sdk/openapi/operation.go
  mgc/sdk/openapi/operation_test.go
Labels: bug

#1238 feat: list bucket size
  mgc/sdk/static/object_storage/buckets/list.go
Labels: enhancement, cli

#1254 fix: typo on TF k8s cluster creation guide
  mgc/terraform-provider-mgc/docs-extra/guides/k8s-cluster-creation.md
  mgc/terraform-provider-mgc/docs/guides/k8s-cluster-creation.md
Labels: documentation

#1256 chore: add PR template to repo
  .github/pull_request_template.md
Labels: documentation

#1255 feat: tf - update block-storage
  .gitignore
  .pre-commit-config.yaml
  mgc/lib/go.mod
  mgc/lib/products/block_storage/snapshots/create.go
  mgc/lib/products/block_storage/snapshots/get.go
  mgc/lib/products/block_storage/snapshots/list.go
  mgc/lib/products/block_storage/volume_types/list.go
  mgc/lib/products/block_storage/volume_types/service.go
  mgc/lib/products/block_storage/volumes/create.go
  mgc/lib/products/block_storage/volumes/get.go
  mgc/lib/products/block_storage/volumes/list.go
  mgc/lib/products/block_storage/volumes/retype.go
  mgc/terraform-provider-mgc/docs/resources/block_storage_snapshots.md
  mgc/terraform-provider-mgc/docs/resources/block_storage_volumes.md
  mgc/terraform-provider-mgc/examples/resources/mgc_block_storage_snapshots/resource.tf
  mgc/terraform-provider-mgc/examples/resources/mgc_block_storage_volumes/resource.tf
  mgc/terraform-provider-mgc/go.mod
  mgc/terraform-provider-mgc/go.sum
  mgc/terraform-provider-mgc/mgc/resources/mgc_bs_snapshots.go
  mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
Labels: terraform

#1258 feat: Add openapi security schema HTTPBearer
  mgc/sdk/openapi/operation.go
Labels: cli, core

#1260 chore: cli release with pr
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  goreleaser_cli.yaml
Labels: pipeline

#1259 feat: tf - remove nodepool validation
  mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go
Labels: terraform

#1262 chore: pr template update
  .github/pull_request_template.md
Labels: pipeline

#1261 fix: adjust output default
  mgc/cli/cmd/output.go
  mgc/cli/go.sum
Labels: cli

#1265 chore: update dbaas instance create terraform documentation
  mgc/terraform-provider-mgc/docs/resources/dbaas_instances.md
  mgc/terraform-provider-mgc/examples/resources/mgc_dbaas_instances/resource.tf
Labels: documentation, terraform

#1269 fix: tf - block storage - volume
  mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
Labels: terraform

#1272 chore: adjust block volume and snapshots to validade if a field can b…
  mgc/terraform-provider-mgc/mgc/resources/mgc_bs_snapshots.go
  mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
  mgc/terraform-provider-mgc/tests/block-storage/main.tf
  mgc/terraform-provider-mgc/tests/block-storage/provider.tf
Labels: terraform
